export const GET_BOARD_REQUEST = 'GET_BOARD_REQUEST'
export const GET_BOARD_SUCCESS = 'GET_BOARD_SUCCESS'
export const GET_BOARD_FAILED = 'GET_BOARD_FAILED'

export const SET_CURRENT_DIFFICULTY = 'SET_CURRENT_DIFFICULTY'
export const SET_BOARD_ARRAY_FORM = 'SET_BOARD_ARRAY_FORM'
export const SET_BOARD_AFTER_ERASE = 'SET_BOARD_AFTER_ERASE'
export const SET_BOARD_AFTER_CLICK_NUMBPAD = 'SET_BOARD_AFTER_CLICK_NUMBPAD'

export const SET_SELECTED_BOARD = 'SET_SELECTED_BOARD'
export const RESET_BOARD_ARRAY_FORM = 'RESET_BOARD_ARRAY_FORM'

export const VALIDATE_BOARD_REQUEST = 'VALIDATE_BOARD_REQUEST'
export const VALIDATE_BOARD_SUCCESS = 'VALIDATE_BOARD_SUCCESS'
export const VALIDATE_BOARD_FAILED = 'VALIDATE_BOARD_FAILED'

export const SOLVE_BOARD_REQUEST = 'SOLVE_BOARD_REQUEST'
export const SOLVE_BOARD_SUCCESS = 'SOLVE_BOARD_SUCCESS'
export const SOLVE_BOARD_FAILED = 'SOLVE_BOARD_FAILED'